"""Add video_id column

Revision ID: 7ff77bdaeb01
Revises: f29c20a53ae6
Create Date: 2024-08-02 22:43:01.430019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff77bdaeb01'
down_revision = 'f29c20a53ae6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sermon_download_progress', sa.Column('video_id', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sermon_download_progress', 'video_id')
    # ### end Alembic commands ###