"""Add sermons_table

Revision ID: f29c20a53ae6
Revises: 
Create Date: 2024-07-24 15:47:10.407916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29c20a53ae6'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sermon_download_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('video_created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('english_caption_uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sermon_download_progress'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sermon_download_progress')
    # ### end Alembic commands ###